const celebrate=document.querySelector('#celebrate');
function fireworks(){const colors=['#ef5c6d','#ffbd4a','#8e67d5','#4d9ce4','#53bf8a','#ff8bb0'];for(let burst=0;burst<7;burst++){const cx=10+Math.random()*80,cy=12+Math.random()*68;setTimeout(()=>{for(let i=0;i<38;i++){const spark=document.createElement('i'),a=Math.random()*Math.PI*2,d=65+Math.random()*190;spark.className='firework';spark.style.setProperty('--fire-x',`${cx}vw`);spark.style.setProperty('--fire-y',`${cy}vh`);spark.style.setProperty('--spark-x',`${Math.cos(a)*d}px`);spark.style.setProperty('--spark-y',`${Math.sin(a)*d}px`);spark.style.setProperty('--spark-color',colors[(i+burst)%colors.length]);spark.style.setProperty('--spark-size',`${7+Math.random()*11}px`);document.body.appendChild(spark);spark.addEventListener('animationend',()=>spark.remove())}},burst*150)}}
celebrate.addEventListener('click',fireworks);
// A three-beat celebration when the page first opens.
[450,1800,3150].forEach(delay=>setTimeout(fireworks,delay));

const modal=document.querySelector('#memory-modal'),closeModal=document.querySelector('#modal-close'),noteTitle=document.querySelector('#note-title'),noteCopy=document.querySelector('#note-copy');
const extraPhotos=`<div class="note-photos"><img src="../assets/IMAGE%202026-08-26%2019%3A52%3A51.jpg" alt="Dancing together at Navratri"><img src="../assets/IMAGE%202026-08-26%2019%3A54%3A21.jpg" alt="Sharing a quiet Navratri moment"></div>`;
document.querySelectorAll('.slice').forEach(card=>card.addEventListener('click',()=>{noteTitle.textContent=card.dataset.noteTitle;noteCopy.innerHTML=card.dataset.gallery?`<p>${card.dataset.noteBefore}</p>${extraPhotos}<p>${card.dataset.noteAfter}</p>`:`<p>${card.dataset.note}</p>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}));
function shut(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}closeModal.addEventListener('click',shut);modal.addEventListener('click',e=>{if(e.target===modal)shut()});addEventListener('keydown',e=>{if(e.key==='Escape')shut()});
const popupCSS=`.memory-modal{position:fixed;z-index:20;inset:0;display:grid;place-items:center;padding:clamp(18px,5vw,72px);background:rgba(48,35,36,.28);backdrop-filter:blur(6px);opacity:0;visibility:hidden;transition:.3s}.memory-modal.open{opacity:1;visibility:visible}.memory-card{position:relative;width:min(900px,100%);height:min(760px,82vh);padding:clamp(38px,6vw,76px);border-radius:52px 52px 52px 14px;background:#fffaf4;box-shadow:0 28px 75px rgba(57,30,33,.28);transform:translateY(25px) scale(.94);transition:transform .42s cubic-bezier(.18,.82,.26,1);overflow:hidden;display:flex;flex-direction:column}.memory-modal.open .memory-card{transform:none}.modal-close{position:absolute;right:25px;top:23px;width:39px;height:39px;border:0;border-radius:50%;background:#fff;color:#38292a;font-size:29px;line-height:34px;cursor:pointer;box-shadow:0 2px 9px rgba(30,20,20,.13)}.note-kicker{margin:0 0 16px;font:10px "DM Mono",monospace;letter-spacing:.14em;color:#cb777c}.memory-card h2{max-width:670px;margin:0;font:400 clamp(46px,7vw,88px)/.83 "Instrument Serif",Georgia,serif;letter-spacing:-.07em;color:#332424}.memory-card #note-copy{max-width:640px;margin:30px 0 0;padding:0 20px 28px 0;overflow-y:auto;font:clamp(13px,1.35vw,16px)/1.85 "DM Mono",monospace;color:#665454;scrollbar-width:thin;scrollbar-color:#dfb8b9 transparent}.memory-card #note-copy::-webkit-scrollbar{width:5px}.memory-card #note-copy::-webkit-scrollbar-thumb{background:#dfb8b9;border-radius:9px}.note-heart{position:absolute;right:clamp(27px,5vw,62px);bottom:clamp(18px,3vw,35px);font:clamp(42px,5vw,68px) Georgia,serif;color:#df7e87;transform:rotate(10deg);pointer-events:none}`;const style=document.createElement('style');style.textContent=popupCSS;document.head.appendChild(style);
const photoCSS=`.memory-card #note-copy{flex:1 1 auto;min-height:0}.note-copy p{margin:0 0 28px}.note-photos{position:relative;max-width:590px;height:330px;margin:3px 20px 34px 0}.note-photos img{position:absolute;width:52%;height:205px;object-fit:cover;border-radius:22px 22px 8px 22px;box-shadow:0 15px 30px rgba(89,54,57,.18);transition:transform .3s ease}.note-photos img:first-child{right:0;top:0;transform:rotate(3deg)}.note-photos img:last-child{left:0;bottom:0;border-radius:22px 22px 22px 8px;transform:rotate(-3deg)}.note-photos img:hover{z-index:2;transform:scale(1.04) rotate(0)}@media(max-width:600px){.note-photos{height:260px}.note-photos img{height:160px;width:58%}}`;const photoStyle=document.createElement('style');photoStyle.textContent=photoCSS;document.head.appendChild(photoStyle);
